### ISSUE TITLE
fatal error: 'ffts.h' file not found

### ISSUE THREAD

**Issue by robclouth** [anthonix/ffts#40]
Hi, I´m trying to build for OSX but I´m getting this error.
I cd´d into the download directory, did ./configure --enable-sse --enable-single --prefix=/usr/local, but then on make I get this error. ffts.h is clearly there, which makes me think the makefile is wrong, but I don´t know enough about them to understand the problem. 
In the makefile there is this:
includedir = ${prefix}/include
If I move ffts.h there (using what I passed in as the prefix arg), the error moves onto malloc.h. So somethings up.

Cheers,

Rob

**Comment by syntheticpp** [comment]
Have you tried with cmake, AFAIK only the cmake build is maintained.

**Comment by robclouth** [comment]
Thanks for the tip. So I did the steps on this page https://github.com/linkotec/ffts
mkdir build
  cd build
  cmake ..
This generated a makefile.
Then I did make, but I get a malloc.h file not found error....

**Comment by lmdsp** [comment]
Yes, malloc.h  includes have to be commented out on XCode, because it's not present.
It will compile fine without it.
Accoring to http://stackoverflow.com/questions/12973311/difference-between-stdlib-h-and-malloc-h it's non-standard and deprecated anyway, so this should probably be marked as a bug and fixed in the source.
